name: Build recovery Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      VENDOR: motorola
      DEVICE: channel
      ANDROID_ROOT: /home/runner/work/orangefox/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo-1 > ~/bin/repo
        chmod +x ~/bin/repo
        git config --global user.name "CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"
    - name: Downloading source code
      run: |
        source of.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0
        repo sync -j8 -c 
        git clone https://github.com/00p513-dev/android_device_motorola_channel-1 -b android-10.0 $ANDROID_ROOT/device/motorola/channel
        git clone https://github.com/CaptainThrowback/android_device_qcom_twrp-common -b android-10 $ANDROID_ROOT/device/qcom/twrp-common
 
    - name: Build recovery
      run: |
        chmod +x build.sh
        bash -x build.sh
      shell: bash

    - name : Upload recovery image
      uses: actions/upload-artifact@master
      with:
        name: Recovery image
        path: /home/runner/work/orangefox/out/target/product/channel/boot.img

    
